### ISSUE TITLE
Categories/ groups cannot be expanded by string[] argument

### ISSUE THREAD

**Issue by aforemny** [IntelliSearch/search-client#15]
Hi,
I have found that categories/ groups cannot be expanded by specifying the group's or category's name as a array of strings.

Steps to reproduce:
- Clone my [category-expansion-on-string](https://github.com/aforemny/search-client/tree/category-expansion-on-string) ([diff](https://github.com/aforemny/search-client/commit/1c166f66122886c1491a353aa1721c6b01bb2a53))
- Run `yarn run samples:plain`
- Try to expand a group or category

**Comment by Spiralis** [comment]
`toggleCategoryExpansion` doesn't actually support array of categories as input (https://intellisearch.github.io/search-client/classes/searchclient.html#togglecategoryexpansion). 

But, it probably should. I will look into adding that.
