### ISSUE TITLE
Trouble building this package due to user permissions

### ISSUE THREAD

**Issue by aforemny** [IntelliSearch/search-client#16]
Hi,
I experienced a problem building this package. On a fresh checkout, if I run `yarn build`, it fails for me at the `build:umd` step with the following error:

```sh
% yarn build:umd
yarn run v1.5.1
$ webpack --config webpack.config.js
Error: EACCES: permission denied, mkdir '/home/temp'
…
```

On Windows I experience the same except with the path `C:\Users\temp` instead of `/home/temp`. I could fix it by setting `compilerOptions.outDir` to some relative path, say `./temp`, inside `tsconfig.json`.

**Comment by Spiralis** [comment]
I cannot reproduce it on my computer (Windows), but it seems like a bug that the tsconfig refers to /temp, so I will fix this.
