### ISSUE TITLE
The matchOrderBy accessor default value is not date, as documented

### ISSUE THREAD

**Issue by TrueCapslock** [IntelliSearch/search-client#5]
The default value of `matchOrderBy` is `OrderBy.Relevance` and not `OrderBy.Date` as documented.
Should the documentation change to reflect this?

**Comment by Spiralis** [comment]
There are three places where the `OrderBy` is involved:

1. [SearchClient.matchOrderBy](https://intellisearch.github.io/search-client/classes/searchclient.html#matchorderby)  
The default for this `SearchClient` class property is whatever is default in the `Query` class - as the values is set on initialization from the `Settings` object's `query` property (passed to the `SearchClient` constructor). 
2. [Query.matchOrderBy](https://intellisearch.github.io/search-client/classes/query.html#matchorderby)
But, this page does say that `Relevance` is the default and it is so in the source too.
3. [OrderBy](https://intellisearch.github.io/search-client/enums/orderby.html)
This is the enum data-type for the `matchOrderBy` property. This datatype has a default set to `Date` (as the Date enum value is 0), both in docs and source.

Now... 
* The `SearchService` *back-end* is set up to make searches *date-ordered by default*. 
* The SearchClient `OrderBy` enum is set up the same way (which I'd say makes sense)
* I guess for consistency we should actually make `Query.matchOrderBy` Date by default too. 
* Then again, the SearchClient will always pass the orderBy param to the back-end, so the defaults can be chosen in the SearchClient as we like.

*Another question is: *
Is `Date` really the best "default"? One could argue that `Relevance` order is probably in most cases going to be the default for the search UI. Changing the default could be done here in the SearchClient, as that would mean that it will always pass it to the back-end anyway.

*So: Two possible solutions: *
1. Make the SearchClient default to `Relevance` (redefining the `OrderBy` enum)
2. Make the SearchClient default to `Date` (redefining the `Query.matchOrderBy` default).

*Where should we go?*
I am aligned to vote for making it `Relevance`by default in the SearchClient. Which it already kind of is, but we should clean up the OrderBy class to be the same, I guess. To reduce confusion if not for anything else.

**Comment by Spiralis** [comment]
Closing with making default Relevance for all types/properties involved.
